f(3)
f(2)
f(1)
defer 0
defer 1
defer 2
defer 3
!!!niki!!!
Traceback (most recent call last):
  File "exception.py", line 22, in <module>
    main()
  File "exception.py", line 3, in main
    f(3)
  File "exception.py", line 16, in f
    f(x - 1)
  File "exception.py", line 16, in f
    f(x - 1)
  File "exception.py", line 16, in f
    f(x - 1)
  File "exception.py", line 15, in f
    print(f"f({x+0//x})")  # raises if x == 0
ZeroDivisionError: integer division or modulo by zero
